<a href="https://colab.research.google.com/github/Gabr-iel007/MachineLearning-projects/blob/main/Numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy is a python library that is used for mathematical operations, working with arrays, scientific computing and data processing



Arrays

An array is a collection of similar data stored together
[10, 4, 1, 5]


In [ ]:
pip install numpy


In [ ]:
import numpy as np

numbers = np.array([1,2,2,3,4,4,5,6,7,7,8,4,3])
print(numbers)

[1 2 2 3 4 4 5 6 7 7 8 4 3]


In [ ]:
import numpy as np

numbers = np.array([1,2,2,3,4,4,5,6,7,7,8,4,3])
print(numbers)

print(numbers[5])
print(numbers[9])
print(numbers[0])
print(numbers[3])
print(numbers[-1])
print(numbers[-2])

[1 2 2 3 4 4 5 6 7 7 8 4 3]
4
7
1
3
3
4


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

c = a + b
d = a * b
print(c)
print(d)

print(a.mean())
print(a.max())

[ 6  8 10 12]
[ 5 12 21 32]
2.5
4


Scikit Learn
Building and training Machine Learning models
Data preprocessing
evaluation
prediction

Task Examples
Classification - Predict spam emails
Regression - predict house prices
clustering - Group customers
Data Scaling - Normalize values
Feature Selection - choose useful columns
Model Evaluation - Check accuracy
Cross Validation - Test reliability

CORE CONCEPTS
features (x) - input data used for prediction
Target (y) - this is what you want to predict
Model - The algorithm that learns patterns from data
Training - teaching the model to use data
prediction - using the model to work
Evaluation - Testing/Checking how good the model performs

In [ ]:
pip install scikit-learn


In [ ]:
import sklearn

